spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cip?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 2002.03.29+LW
  banner:
    location:

server:
  port: 8099
  servlet:
    context-path: "/cip"
