spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.129.219:3306/cip?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 20020329@mysql
    druid:
      transaction-query-timeout: 10

  #邮件发送相关
  mail:
    host: smtp.qq.com
    port: 4658099
    username: '3065242502@qq.com'
    #授权码
    password: 'neaymokwnojhdfad'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  mvc:
    #路径匹配，防止SpringBoot2.6过后与swagger冲突的问题
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: dev

server:
  port: 8099
  servlet:
    context-path: "/cip"

chatGPT:
  openAiApiBaseUrl: https://api.openai.com/
  openAiApiKey: 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
  #代理
  proxyHostName: kaolacode.f3322.net
  proxyPort: 10809

mybatis-plus:
  configuration:
    #日志打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#http://localhost:8099/cip/html/login.html 登录网址