spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.129.219:3306/cip?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 20020329@mysql
  banner:
    location:

server:
  port: 8099
  servlet:
    context-path: "/cip"
