spring:
  #数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.33.242.250/cip?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 20020329@mysql
      transaction-query-timeout: 10

  #邮件发送相关
  mail:
    host: smtp.qq.com
    username: 3065242502@qq.com
    #授权码
    password: ntjmesynmcasddde
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  mvc:
    #路径匹配，防止SpringBoot2.6过后与swagger冲突的问题
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    # 指定json解析时的日期格式
    date-format: yyyy-MM-dd HH:mm
    # 设置时区
    time-zone: Asia/Shanghai

  profiles:
    active: dev

  # redis相关
  redis:
    host: 101.33.242.250
    port: 6379
    client-type: lettuce

  # 缓存相关
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: cip_
      time-to-live: 300s
      cache-null-values: true


#  # mongodb相关
#  data:
#    mongodb:
#      uri: mongodb://106.12.129.219/first_db

server:
  port: 8099
  servlet:
    context-path: "/cip"

chatGPT:
  openAiApiBaseUrl: https://api.openai.com/
  openAiApiKey: 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
  #代理
  proxyHostName: kaolacode.f3322.net
  proxyPort: 10809

mybatis-plus:
  configuration:
    # 日志打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#http://localhost:8099/cip/html/login.html 登录网址
